# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
